spring:
  application:
    name: rb-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gujiachun/rb-config.git
    
server:
  port: 8750
     
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka